# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  marrano-bot = {
    pname = "marrano-bot";
    version = "5438411f04eb1d02aafe8b06a2b906bd37f13218";
    src = fetchFromGitHub {
      owner = "moolite";
      repo = "bot";
      rev = "5438411f04eb1d02aafe8b06a2b906bd37f13218";
      fetchSubmodules = false;
      sha256 = "sha256-8lUreZteJs9bKIbyKeO+8s/f60W8kov1Hw8dDC7GxcA=";
    };
    date = "2023-03-22";
  };
  tfenv = {
    pname = "tfenv";
    version = "1ccfddb22005b34eacaf06a9c33f58f14e816ec9";
    src = fetchFromGitHub {
      owner = "tfutils";
      repo = "tfenv";
      rev = "1ccfddb22005b34eacaf06a9c33f58f14e816ec9";
      fetchSubmodules = false;
      sha256 = "sha256-UNvLJQB47IRcNZpoUGXTW2g63ApijnIB3oUb7Zu4lUY=";
    };
    date = "2022-10-01";
  };
}
